name: Build & deploy to gh-pages

on:
  push:
    branches: 'master'

# Nicked from https://kit.svelte.dev/docs/adapter-static
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: build
        env:
          BASE_PATH: '/your-repo-name'
        run: |
          pnpm run build
          touch build/.nojekyll
          cp CNAME build/CNAME

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1

# name: Build the site and push to the gh-pages branch

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Build and Push
#     steps:
#       - name: git-checkout
#         uses: actions/checkout@v2

#       - name: Install full dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Copy settings files
#         run: cp .nojekyll out/.nojekyll && cp CNAME out/CNAME

#       - name: Push
#         uses: s0/git-publish-subdir-action@develop
#         env:
#           REPO: self
#           BRANCH: gh-pages
#           FOLDER: out
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           MESSAGE: "Build: ({sha}) {msg}"
